language: objective-c
osx_image: xcode7.1

script:

    - xcodebuild -project Example/FSCalendar.xcodeproj -sdk iphonesimulator -alltargets
    - xcodebuild -project SwiftExample/SwiftExample.xcodeproj -sdk iphonesimulator -alltargets